/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "primary-fixed": "#c9f308",
        "tertiary-container": "#ffde5d",
        "on-primary": "#ffffff",
        "on-background": "#1b1b1b",
        "on-primary-fixed": "#171e00",
        primary: "#536600",
        "inverse-primary": "#b0d500",
        background: "#f9f9f9",
        "on-surface": "#1b1b1b",
        surface: "#f9f9f9",
        "on-primary-container": "#576a00",
        secondary: "#006492",
        "secondary-container": "#0cb3ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#004261",
        "surface-variant": "#e2e2e2",
        "on-secondary": "#ffffff",
        "outline-variant": "#c5c9ad",
        "surface-container-low": "#f3f3f3",
        "inverse-surface": "#303030",
        "on-surface-variant": "#444933",
        "surface-container": "#eeeeee",
        "primary-fixed-dim": "#b0d500",
        "surface-container-high": "#e8e8e8",
        "primary-container": "#c7f000",
        outline: "#757961",
        tertiary: "#705d00",
        "surface-dim": "#dadada",
        "surface-container-highest": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        base: "8px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        "container-margin": "20px",
        gutter: "16px",
        xs: "4px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}